# Generated by Django 3.0.6 on 2020-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_lost_ping_host_success_ping_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_ping_host',
            name='hotel_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='success_ping_hosts',
            name='hotel_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
