# Generated by Django 3.0.6 on 2020-09-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200830_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lost_Ping_Host',
        ),
        migrations.DeleteModel(
            name='Success_Ping_Hosts',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
