# Generated by Django 3.0.6 on 2020-07-18 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 9, 36, 27, 222949)),
        ),
        migrations.AddField(
            model_name='hotels',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 9, 36, 27, 222016)),
        ),
    ]
