# Generated by Django 3.0.6 on 2020-07-18 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0002_auto_20200718_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('ip_address_v4', models.GenericIPAddressField(default='0.0.0.0')),
                ('hotel_admin_id', models.CharField(max_length=6)),
                ('port', models.CharField(default='22', max_length=10)),
                ('ipvpn_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('portvpn', models.CharField(default='22', max_length=10)),
                ('create_data', models.DateField(auto_now_add=True)),
                ('date_of_creation_certificate', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 11, 51, 16, 77577))),
            ],
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.AlterField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 11, 51, 16, 78547)),
        ),
    ]
