# Generated by Django 3.0.6 on 2020-07-18 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0003_auto_20200718_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='city',
            new_name='hotel_city',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='country',
            new_name='hotel_country',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='create_data',
            new_name='hotel_create_data',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='ip_address_v4',
            new_name='hotel_ip_address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='short_name',
            new_name='hotel_name_certification',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='port',
            new_name='hotel_port',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='portvpn',
            new_name='hotel_portvpn',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='ipvpn_address',
            new_name='hotel_vpn_address',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 23, 34, 138846)),
        ),
        migrations.AlterField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 23, 34, 139760)),
        ),
    ]
