# Generated by Django 3.0.6 on 2020-07-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0005_auto_20200718_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 14, 10, 32, 708167)),
        ),
        migrations.AlterField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 14, 10, 32, 709106)),
        ),
    ]
