# Generated by Django 3.0.6 on 2020-07-18 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0006_auto_20200718_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_create_data',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 14, 15, 15, 657869)),
        ),
        migrations.AlterField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 14, 15, 15, 658771)),
        ),
    ]
