# Generated by Django 3.0.6 on 2020-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0007_auto_20200718_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='date_of_creation_certificate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_portvpn',
            field=models.CharField(blank=True, default='22', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(),
        ),
    ]
