# Generated by Django 3.0.6 on 2020-07-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0009_auto_20200718_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_portvpn',
            field=models.CharField(blank=True, default='22', max_length=10),
        ),
    ]
