# Generated by Django 3.0.6 on 2020-07-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0015_auto_20200718_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='date_of_creation_certificate',
        ),
    ]
