# Generated by Django 3.0.6 on 2020-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0017_remove_hotel_user_date_of_creation_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='date_of_creation_certificate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel_user',
            name='date_of_creation_certificate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
