# Generated by Django 3.0.6 on 2020-07-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0018_auto_20200719_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='date_of_creation_certificate',
            new_name='hotel_date_of_creation_certificate',
        ),
        migrations.RenameField(
            model_name='hotel_user',
            old_name='date_of_creation_certificate',
            new_name='user_date_of_creation_certificate',
        ),
    ]
