# Generated by Django 3.0.6 on 2020-07-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0019_auto_20200719_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_vpn_address',
            new_name='hotel_vpn_ip_address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_portvpn',
            new_name='hotel_vpn_port',
        ),
    ]
