# Generated by Django 3.0.6 on 2020-07-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0021_auto_20200719_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_date_of_creation_certificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
