# Generated by Django 3.0.6 on 2020-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0024_hotel_hotel_ping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_date_of_creation_certificate',
            field=models.CharField(default='no create', max_length=10),
        ),
    ]
