# Generated by Django 3.0.6 on 2020-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsrvpn', '0025_auto_20200907_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', null=True),
        ),
    ]
