# Generated by Django 3.0.6 on 2020-12-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installed_packeges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100)),
                ('installed', models.CharField(blank=True, max_length=200)),
                ('non_install', models.CharField(blank=True, max_length=200)),
                ('task_completed', models.CharField(blank=True, max_length=200)),
                ('task_non_completed', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task_and_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100, unique=True)),
                ('task', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('git_task', models.CharField(blank=True, max_length=100)),
                ('git_status', models.IntegerField(default=0)),
            ],
        ),
    ]
