# Generated by Django 3.0.6 on 2020-06-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0003_tasl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasl',
            new_name='Task',
        ),
    ]
