# Generated by Django 3.0.6 on 2020-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installed_packeges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_package', models.CharField(max_length=200)),
                ('non_install_package', models.CharField(max_length=200)),
            ],
        ),
    ]
