# Generated by Django 3.0.6 on 2020-06-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0006_installed_packeges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installed_packeges',
            old_name='installed_package',
            new_name='installed',
        ),
        migrations.RenameField(
            model_name='installed_packeges',
            old_name='non_install_package',
            new_name='non_install',
        ),
    ]
