# Generated by Django 3.0.6 on 2020-07-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0008_auto_20200630_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='SaveConfig',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
