# Generated by Django 3.0.6 on 2020-07-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0010_completed_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed_tasks',
        ),
        migrations.AddField(
            model_name='installed_packeges',
            name='task_completed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='installed_packeges',
            name='task_non_completed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
