# Generated by Django 3.0.6 on 2020-09-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0011_auto_20200711_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy_status_bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bar', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
