# Generated by Django 3.0.6 on 2020-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_client', '0012_deploy_status_bar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deploy_status_bar',
        ),
        migrations.AddField(
            model_name='installed_packeges',
            name='hotel_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
